ignore:
- "*/package.d"

coverage:
  range: 70..90
  round: up
  precision: 2
  status:
    project:
      default:
        enabled: yes
        target: 70%
        threshold: 10%
    patch:
      default:
        enabled: yes
        target: 70%
        threshold: 10%
