
language: d

d:
    - dmd
    - ldc-1.19.0
os:
    - linux
env:
    - BUILD_TYPE=debug
    - BUILD_TYPE=unittest

matrix:
  include:
  - d: dmd
    env: BUILD_TYPE=unittest-cov
  exclude:
  - d: dmd
    env: BUILD_TYPE=unittest

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev

script:
- ./travis.sh
