
language: d

d:
    - dmd-2.078.3
    - dmd-2.078.2
os:
    - linux
env:
    - BUILD_TYPE=debug
    - BUILD_TYPE=unittest

matrix:
  include:
  - d: dmd-2.078.3
    env: BUILD_TYPE=unittest-cov
  exclude:
  - d: dmd-2.078.3
    env: BUILD_TYPE=unittest

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev

script:
- ./travis.sh
